In [6]:
a = 2

In [7]:
a = a + 2

In [8]:
print(a)

4


In [9]:
import numpy as np
a = np.arange(18)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [15]:
a.reshape(-1, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [16]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [18]:
b = a.reshape(3, -1)

In [20]:
c = b[0]

In [21]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [22]:
c

array([0, 1, 2, 3, 4, 5])

In [23]:
np.shares_memory(b, c)

True

In [24]:
np.shares_memory(a, b)

True

In [29]:
c[0] = 100
print(c)
print(b)
print(a)

[100   1   2   3   4   5]
[[100   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
